export const INPUT_PRESETS = [
  {
    type: 'theme',
    value: '雨天旧书店',
    subject: 'old bookstore',
    mood: 'quiet',
  },
  {
    type: 'theme',
    value: '海边午后',
    subject: 'seaside afternoon',
    mood: 'afternoon',
  },
  {
    type: 'theme',
    value: '台风记忆',
    subject: 'typhoon memory',
    mood: 'memory',
  },
  {
    type: 'theme',
    value: '夜门',
    subject: 'night gate',
    mood: 'night',
  },
];

export const VARIATION_RECIPES = [
  {
    id: 'center-fragment-cobalt',
    layout: 'center-fragment',
    anchor: 'tiny faded photo',
    typography: 'fragmented floating letters',
    accent: 'cobalt blue',
    texture: 'xerox softness',
    mood: 'quiet',
  },
  {
    id: 'lower-left-float-ultramarine',
    layout: 'lower-left-float',
    anchor: 'torn-paper clipping',
    typography: 'short phrase pressed against image edge',
    accent: 'ultramarine',
    texture: 'risograph grain',
    mood: 'solitude',
  },
  {
    id: 'upper-right-block-magenta',
    layout: 'upper-right-block',
    anchor: 'solid color block',
    typography: 'archive microtext with date/weather',
    accent: 'magenta-pink',
    texture: 'letterpress ink bleed',
    mood: 'afternoon',
  },
  {
    id: 'dual-panel-lemon',
    layout: 'dual-panel',
    anchor: 'old printed illustration',
    typography: 'diagonal scattered words',
    accent: 'lemon yellow',
    texture: 'halftone degradation',
    mood: 'childhood',
  },
  {
    id: 'irregular-cutout-pear',
    layout: 'irregular-cutout',
    anchor: 'object specimen',
    typography: 'low-contrast gray ghost text',
    accent: 'pear green',
    texture: 'scan noise and paper fibers',
    mood: 'memory',
  },
  {
    id: 'single-specimen-tomato',
    layout: 'single-specimen',
    anchor: 'abstract texture window',
    typography: 'almost textless, only a tiny caption',
    accent: 'tomato red',
    texture: 'aged paper mottling',
    mood: 'night',
  },
  {
    id: 'lower-left-float-cobalt',
    layout: 'lower-left-float',
    anchor: 'torn-paper clipping',
    typography: 'short phrase pressed against image edge',
    accent: 'cobalt blue',
    texture: 'risograph grain',
    mood: 'solitude',
  },
  {
    id: 'center-fragment-tomato',
    layout: 'center-fragment',
    anchor: 'tiny faded photo',
    typography: 'fragmented floating letters',
    accent: 'tomato red',
    texture: 'xerox softness',
    mood: 'quiet',
  },
  {
    id: 'upper-right-block-ultramarine',
    layout: 'upper-right-block',
    anchor: 'solid color block',
    typography: 'archive microtext with date/weather',
    accent: 'ultramarine',
    texture: 'letterpress ink bleed',
    mood: 'afternoon',
  },
];

export const QUALITY_RULES = [
  '3:5 vertical canvas',
  '70%-90% negative space',
  'one clear visual anchor',
  'explicit saturated hue',
  'print/scan texture',
  'hard avoid phrase',
];

export const ASSET_MANIFEST = [
  { id: 'paper-a', role: 'paper tone', file: 'paper-toned-01.png' },
  { id: 'paper-b', role: 'paper tone', file: 'paper-toned-02.png' },
  { id: 'texture-a', role: 'scan texture', file: 'scan-noise-01.png' },
  { id: 'type-a', role: 'typography sample', file: 'microtype-01.png' },
  {
    id: 'rainy-bookstore',
    sourceTheme: 'old bookstore',
    assetPath: 'assets/generated/rainy-bookstore.jpeg',
    prompt:
      'Minimal zine-style poster, vertical 3:5 composition, lower-left-float layout. A torn-paper clipping of a quiet old bookstore window sits low and left as the single subject. 70% to 90% of the canvas is aged off-white paper negative space. One fully saturated cobalt-blue book spine is the dominant chromatic anchor. Add subtle print/scan texture, paper fibers, and sparse tiny type or omit text. Style/medium: flat printed collage, risograph-meets-photocopy zine poster. Composition/framing: one small bookstore window fragment, generous empty paper field, readable at thumbnail size. Lighting/mood: calm, muted, overcast memory without cinematic lighting. Color palette: mostly warm aged paper, charcoal neutrals, one vivid cobalt blue accent. Materials/textures: torn paper edges, ink softness, scan wear. Constraints: no commercial ad layout, no glossy mockup, no 3D, no neon, no cinematic lighting, no dense scrapbook, no long clean text block, no watermark.',
    recipeId: 'lower-left-float-cobalt',
    accentColor: 'cobalt blue',
    generatedAt: '2026-08-01',
    note: 'GENERATED SAMPLE',
  },
  {
    id: 'seaside-pause',
    sourceTheme: 'seaside afternoon',
    assetPath: 'assets/generated/seaside-pause.jpeg',
    prompt:
      'Minimal zine-style poster, vertical 3:5 composition, center-fragment layout. A small shell or tide specimen is the single clear subject near center. Include one vivid tomato-red printed block as the dominant chromatic anchor. Keep 70% to 90% of the poster as aged paper negative space. Add xerox softness, scan noise, and very sparse caption-like type or no text. Style/medium: photocopied editorial collage on paper. Composition/framing: tiny centered specimen, lots of blank paper around it, easy to read as a thumbnail. Lighting/mood: quiet seaside pause, soft and matter-of-fact, not cinematic. Color palette: warm paper, gray-black print, one saturated tomato red accent. Materials/textures: xerox blur, paper fibers, subtle registration drift. Constraints: no commercial ad layout, no glossy mockup, no 3D, no neon, no cinematic lighting, no dense scrapbook, no long clean text block, no watermark.',
    recipeId: 'center-fragment-tomato',
    accentColor: 'tomato red',
    generatedAt: '2026-08-01',
    note: 'GENERATED SAMPLE',
  },
  {
    id: 'typhoon-memory',
    sourceTheme: 'typhoon memory',
    assetPath: 'assets/generated/typhoon-memory.jpeg',
    prompt:
      'Minimal zine-style poster, vertical 3:5 composition, dual-panel layout. Two small weather-memory fragments appear as separated printed scraps. A fully opaque lemon-yellow raincoat or raincoat cutout is the single chromatic anchor. Keep 70% to 90% of the canvas as aged paper negative space. Add halftone degradation, archive wear, and sparse short type or omit text. Style/medium: degraded printed collage, memory fragments on paper. Composition/framing: two small panels/fragments with strong empty field, readable at thumbnail size. Lighting/mood: typhoon memory, restrained and tactile, no cinematic lighting. Color palette: paper beige, washed charcoal, one saturated lemon yellow accent. Materials/textures: halftone dots, torn edges, scan wear. Constraints: no commercial ad layout, no glossy mockup, no 3D, no neon, no cinematic lighting, no dense scrapbook, no long clean text block, no watermark.',
    recipeId: 'dual-panel-lemon',
    accentColor: 'lemon yellow',
    generatedAt: '2026-08-01',
    note: 'GENERATED SAMPLE',
  },
  {
    id: 'night-door',
    sourceTheme: 'night gate',
    assetPath: 'assets/generated/night-door.jpeg',
    prompt:
      'Minimal zine-style poster, vertical 3:5 composition, upper-right-block layout. An isolated night door or small night object fragment sits toward the upper right as the single subject. Include one fully saturated ultramarine printed block as the dominant chromatic anchor. Keep 70% to 90% of the canvas as aged paper negative space. Add letterpress bleed, paper fibers, and tiny sparse type or no text. Style/medium: quiet night collage print, zine poster. Composition/framing: small subject in upper-right area, large empty paper field, clear at thumbnail size. Lighting/mood: nocturnal but flat and printed, not cinematic. Color palette: warm paper, ink black, one vivid ultramarine accent. Materials/textures: slight ink bleed, paper grain, print wear. Constraints: no commercial ad layout, no glossy mockup, no 3D, no neon, no cinematic lighting, no dense scrapbook, no long clean text block, no watermark.',
    recipeId: 'upper-right-block-ultramarine',
    accentColor: 'ultramarine',
    generatedAt: '2026-08-01',
    note: 'GENERATED SAMPLE',
  },
  {
    id: 'indie-zine-cover',
    scenarioId: 'indie-zine-cover',
    sourceTheme: 'rain-softened library card and old bookstore window',
    assetPath: 'assets/generated/scenarios/indie-zine-cover.jpeg',
    prompt:
      'Use case: product-mockup / independent zine cover. Asset type: single-issue editorial cover. Primary request: a rain-softened library card beside a quiet old bookstore window, with a cobalt-blue book spine as the only vivid anchor. The cover should feel collectable and printed, not like a commercial book advertisement. Scene/backdrop: vertical 3:5 aged paper, 70%–90% negative space. Subject: one small paper card and bookstore fragment, recognizable at thumbnail size. Style/medium: photocopy and risograph zine collage, tactile paper and worn ink. Composition/framing: small lower-left fragment with a huge open paper field, no readable generated words. Lighting/mood: rainy, quiet, editorial, flat printed atmosphere. Color palette: warm paper, charcoal ink, one saturated cobalt-blue accent. Materials/textures: paper fibers, scan grain, torn edges, slight registration error. Text (verbatim): none; no readable generated words. Constraints: portrait 3:5, one clear anchor, editorial cover concept, no watermark. Avoid: commercial ad layout, glossy mockup, 3D render, neon, cinematic lighting, dense scrapbook collage, long clean text block, multiple focal subjects.',
    recipeId: 'lower-left-float-cobalt',
    accentColor: 'cobalt blue',
    generatedAt: '2026-08-01',
    note: 'GENERATED SCENARIO SAMPLE',
  },
  {
    id: 'bookstore-event',
    scenarioId: 'bookstore-event',
    sourceTheme: 'small reading table after bookstore closing',
    assetPath: 'assets/generated/scenarios/bookstore-event.jpeg',
    prompt:
      'Use case: product-mockup / bookstore event poster. Asset type: weekend reading event poster. Primary request: a small lit reading table after closing, with a tomato-red book spine as the only vivid anchor. Leave the rest of the paper open for a later event title, not a commercial promotion. Scene/backdrop: vertical 3:5 aged paper, 70%–90% negative space. Subject: one small reading table, books and a quiet lamp, recognizable at thumbnail size. Style/medium: photocopy zine collage, restrained risograph, tactile paper. Composition/framing: a small lower-left or lower-right corner scene with a large open paper field, no readable generated words. Lighting/mood: after-hours, intimate, calm, flat printed atmosphere. Color palette: warm paper, charcoal ink, one saturated tomato-red accent. Materials/textures: scan grain, paper fibers, worn ink, slight registration drift. Text (verbatim): none; no readable generated words. Constraints: portrait 3:5, one clear anchor, cultural event poster concept, no watermark. Avoid: commercial ad layout, glossy mockup, 3D render, neon, cinematic lighting, dense scrapbook collage, long clean text block, multiple focal subjects.',
    recipeId: 'center-fragment-tomato',
    accentColor: 'tomato red',
    generatedAt: '2026-08-01',
    note: 'GENERATED SCENARIO SAMPLE',
  },
  {
    id: 'cafe-seasonal',
    scenarioId: 'cafe-seasonal',
    sourceTheme: 'shell and half-finished cold brew by the sea',
    assetPath: 'assets/generated/scenarios/cafe-seasonal.jpeg',
    prompt:
      'Use case: product-mockup / seasonal cafe poster. Asset type: seasonal menu or window poster. Primary request: a shell and half-finished cold brew on a seaside cafe counter, with a lemon-yellow receipt or napkin as the only vivid anchor. It should feel light and tactile, not like a chain cafe promotion. Scene/backdrop: vertical 3:5 aged paper, 70%–90% negative space. Subject: one small shell and one cup fragment treated as a single visual anchor. Style/medium: flat photocopy and risograph collage, worn paper. Composition/framing: small lower-left or center fragment with generous open paper field, no readable generated words. Lighting/mood: breezy, seasonal, quiet, matter-of-fact, non-cinematic. Color palette: warm paper, charcoal ink, one saturated lemon-yellow accent. Materials/textures: scan wear, paper fibers, soft ink, slight registration error. Text (verbatim): none; no readable generated words. Constraints: portrait 3:5, one clear anchor, cafe editorial concept, no watermark. Avoid: commercial ad layout, glossy mockup, 3D render, neon, cinematic lighting, dense scrapbook collage, long clean text block, multiple focal subjects.',
    recipeId: 'single-specimen-tomato',
    accentColor: 'lemon yellow',
    generatedAt: '2026-08-01',
    note: 'GENERATED SCENARIO SAMPLE',
  },
  {
    id: 'art-exhibition',
    scenarioId: 'art-exhibition',
    sourceTheme: 'two weather fragments after a typhoon',
    assetPath: 'assets/generated/scenarios/art-exhibition.jpeg',
    prompt:
      'Use case: product-mockup / exhibition key visual. Asset type: contemporary art exhibition poster. Primary request: two weather fragments after a typhoon, with an opaque ultramarine panel as the only vivid conceptual anchor. The image should suggest an exhibition argument without becoming a busy gallery advertisement. Scene/backdrop: vertical 3:5 aged paper, 70%–90% negative space. Subject: two small printed weather fragments treated as one visual idea. Style/medium: degraded photocopy collage, restrained risograph, archival paper. Composition/framing: separated fragments with a large open paper field, no readable generated words. Lighting/mood: contemplative, observational, non-cinematic. Color palette: warm paper, washed charcoal, one saturated ultramarine accent. Materials/textures: halftone dots, torn edges, scan softness, imperfect registration. Text (verbatim): none; no readable generated words. Constraints: portrait 3:5, one clear conceptual anchor, exhibition poster restraint, no watermark. Avoid: commercial ad layout, glossy mockup, 3D render, neon, cinematic lighting, dense scrapbook collage, long clean text block, multiple focal subjects.',
    recipeId: 'dual-panel-lemon',
    accentColor: 'ultramarine',
    generatedAt: '2026-08-01',
    note: 'GENERATED SCENARIO SAMPLE',
  },
  {
    id: 'poetry-book',
    scenarioId: 'poetry-book',
    sourceTheme: 'unopened night door',
    assetPath: 'assets/generated/scenarios/poetry-book.jpeg',
    prompt:
      'Use case: product-mockup / literary book cover. Asset type: poetry or short-fiction cover. Primary request: an isolated night door with a magenta paper edge as the only vivid anchor. The mood should let emotion arrive before narrative and should not resemble a crowded thriller poster. Scene/backdrop: vertical 3:5 aged paper, 70%–90% negative space. Subject: one small closed or half-seen door fragment, recognizable at thumbnail size. Style/medium: photocopy zine collage, worn paper, flat print. Composition/framing: small lower-right subject with a huge open paper field for later type, no readable generated words. Lighting/mood: literary, suspended, quiet, non-cinematic. Color palette: warm paper, charcoal ink, one saturated magenta-pink accent. Materials/textures: torn paper, scan grain, ink bleed, paper fibers. Text (verbatim): none; no readable generated words. Constraints: portrait 3:5, one clear anchor, literary cover restraint, no watermark. Avoid: commercial ad layout, glossy mockup, 3D render, neon, cinematic lighting, dense scrapbook collage, long clean text block, multiple focal subjects.',
    recipeId: 'upper-right-block-magenta',
    accentColor: 'magenta pink',
    generatedAt: '2026-08-01',
    note: 'GENERATED SCENARIO SAMPLE',
  },
  {
    id: 'music-ep-cover',
    scenarioId: 'music-ep-cover',
    sourceTheme: 'seaside radio and tide mark at 2 a.m.',
    assetPath: 'assets/generated/scenarios/music-ep-cover.jpeg',
    prompt:
      'Use case: product-mockup / independent music release. Asset type: single or EP cover. Primary request: a small seaside radio and a tide mark at 2 a.m., with a cobalt-blue signal block as the only vivid anchor. Quiet nocturnal independent music cover, not a glossy streaming ad. Scene/backdrop: vertical 3:5 aged paper, 70%–90% negative space. Subject: one small old radio or speaker and minimal tide trace, recognizable at thumbnail size. Style/medium: photocopy/riso zine collage, tactile paper, worn ink. Composition/framing: small lower-left or center fragment, huge open paper field, no readable generated words. Lighting/mood: nocturnal, low-volume, calm, flat printed atmosphere, no cinematic lighting. Color palette: warm paper, charcoal ink, one saturated cobalt-blue accent. Materials/textures: scan grain, ink drift, paper fibers, slight registration error. Text (verbatim): none; no readable generated words. Constraints: portrait 3:5, one clear anchor, editorial album-cover concept, no watermark. Avoid: commercial ad layout, glossy mockup, 3D render, neon, cinematic lighting, dense scrapbook collage, long clean text block, multiple focal subjects.',
    recipeId: 'lower-left-float-cobalt',
    accentColor: 'cobalt blue',
    generatedAt: '2026-08-01',
    note: 'GENERATED SCENARIO SAMPLE',
  },
  {
    id: 'museum-culture',
    scenarioId: 'museum-culture',
    sourceTheme: 'worn local object softened by sea wind',
    assetPath: 'assets/generated/scenarios/museum-culture.jpeg',
    prompt:
      'Use case: product-mockup / museum editorial poster. Asset type: museum collection research poster. Primary request: one worn local object softened by sea wind on archival paper, with a tomato-red catalog mark as the only vivid accent. The mood should feel like a quiet cultural institution poster, not a tourist advertisement. Scene/backdrop: vertical 3:5 aged archival paper, 70%–90% negative space. Subject: one small weathered object specimen, recognizable at thumbnail size. Style/medium: flat archival photocopy collage, restrained risograph, paper fibers and print wear. Composition/framing: single specimen in lower-left or lower-right area, expansive open paper field. Lighting/mood: careful, historical, contemplative, non-cinematic. Color palette: warm archival paper, charcoal ink, one saturated tomato-red mark. Materials/textures: torn paper, archive grain, letterpress bleed, scan softness. Text (verbatim): none; no readable generated words. Constraints: portrait 3:5, one clear anchor, editorial museum restraint, no watermark. Avoid: commercial ad layout, glossy mockup, 3D render, neon, cinematic lighting, dense scrapbook collage, long clean text block, multiple focal subjects.',
    recipeId: 'single-specimen-tomato',
    accentColor: 'tomato red',
    generatedAt: '2026-08-01',
    note: 'GENERATED SCENARIO SAMPLE',
  },
  {
    id: 'film-title-card',
    scenarioId: 'film-title-card',
    sourceTheme: 'half-seen night entrance',
    assetPath: 'assets/generated/scenarios/film-title-card.jpeg',
    prompt:
      'Use case: product-mockup / short-film title card concept. Asset type: title card and poster direction. Primary request: a half-seen night entrance or door with a lemon-yellow threshold mark as the only saturated anchor. Suggest an unresolved story without becoming a cinematic movie poster. Scene/backdrop: vertical 3:5 aged paper, 70%–90% empty field. Subject: one small threshold fragment, recognizable at thumbnail size. Style/medium: photocopy zine collage, worn paper, flat print, sparse archival atmosphere. Composition/framing: small upper-right or lower-left subject with large open title area, no readable generated text. Lighting/mood: tense but quiet, nocturnal, non-cinematic. Color palette: warm paper, charcoal black, one saturated lemon-yellow mark. Materials/textures: torn edges, ink bleed, scan wear, paper fibers. Text (verbatim): none; no readable generated words. Constraints: portrait 3:5, one clear visual anchor, title-card restraint, no watermark. Avoid: commercial ad layout, glossy mockup, 3D render, neon, cinematic lighting, dense scrapbook collage, long clean text block, multiple focal subjects.',
    recipeId: 'upper-right-block-ultramarine',
    accentColor: 'lemon yellow',
    generatedAt: '2026-08-01',
    note: 'GENERATED SCENARIO SAMPLE',
  },
  {
    id: 'art-direction',
    scenarioId: 'art-direction',
    sourceTheme: 'cobalt swatch, torn paper, quiet window and abstract type',
    assetPath: 'assets/generated/scenarios/art-direction.jpeg',
    prompt:
      'Use case: productivity-visual / creative direction board. Asset type: sparse art-direction moodboard. Primary request: a cobalt swatch, torn paper, a quiet window fragment, and one restrained type specimen arranged as an editorial direction board. No readable text, no dense scrapbook. Scene/backdrop: vertical 3:5 aged paper, 70%–90% negative space. Subject: a small set of related material samples treated as one clear direction anchor. Style/medium: flat printed collage, risograph, photocopy, tactile paper fibers. Composition/framing: organized but sparse, one lower-left cluster and large open paper field. Lighting/mood: calm, considered, exploratory, not cinematic. Color palette: warm paper, charcoal ink, one saturated cobalt-blue swatch. Materials/textures: torn paper, scan grain, imperfect registration, worn ink. Text (verbatim): none; any type specimen must be abstract marks, not readable words. Constraints: portrait 3:5, one coherent visual anchor, art-direction board, no watermark. Avoid: commercial ad layout, glossy mockup, 3D render, neon, cinematic lighting, dense scrapbook collage, long clean text block, many unrelated objects.',
    recipeId: 'center-fragment-cobalt',
    accentColor: 'cobalt blue',
    generatedAt: '2026-08-01',
    note: 'GENERATED SCENARIO SAMPLE',
  },
  {
    id: 'postcard-insert',
    scenarioId: 'postcard-insert',
    sourceTheme: 'small wrapped object and abstract thank-you mark',
    assetPath: 'assets/generated/scenarios/postcard-insert.jpeg',
    prompt:
      'Use case: product-mockup / small-brand packaging insert. Asset type: thank-you postcard or package insert concept. Primary request: one carefully wrapped small object and a simple abstract thank-you mark on warm paper, with ultramarine as the only vivid accent. It should feel tactile and personal, not like a discount coupon. Scene/backdrop: vertical 3:5 aged paper, 70%–90% negative space. Subject: one small wrapped object and one abstract blue mark, recognizable at thumbnail size. Style/medium: printed zine collage, photocopy and risograph texture, torn paper edges. Composition/framing: small lower-right or center fragment, generous open paper field for later production text; do not generate readable words. Lighting/mood: warm, personal, quiet, non-commercial. Color palette: warm paper, charcoal ink, one saturated ultramarine accent. Materials/textures: paper fibers, soft ink, scan wear, slight registration drift. Text (verbatim): none; no readable generated words. Constraints: portrait 3:5, one clear anchor, postcard/insert concept, no watermark. Avoid: commercial ad layout, glossy mockup, 3D render, neon, cinematic lighting, dense scrapbook collage, long clean text block, multiple focal subjects.',
    recipeId: 'lower-left-float-ultramarine',
    accentColor: 'ultramarine',
    generatedAt: '2026-08-01',
    note: 'GENERATED SCENARIO SAMPLE',
  },
];

export const SCENARIO_SHOWCASES = [
  {
    id: 'indie-zine-cover',
    category: '独立出版 / ZINE',
    audience: '独立编辑、出版人',
    product: '单期杂志封面',
    brief: '雨天旧书店里遗落的一张借书卡',
    visualGoal: '用一个小型纸片主体和大面积旧纸留白，让封面像可收藏的印刷物。',
    whyItFits: '这个 Skill 擅长把一个安静的物件变成有编辑感的视觉锚点。',
    deliverables: ['封面', '目录页视觉', '社交预览'],
    assetId: 'indie-zine-cover',
    accentColor: 'cobalt blue',
  },
  {
    id: 'bookstore-event',
    category: '线下活动',
    audience: '书店主理人',
    product: '周末读书会海报',
    brief: '雨夜书店的闭店后阅读会',
    visualGoal: '把小型阅读桌或书脊放在角落，给活动标题留下呼吸空间。',
    whyItFits: '留白让门店海报不必像促销广告，也能保持文化活动的安静气质。',
    deliverables: ['门店海报', '桌卡', '活动帖图'],
    assetId: 'bookstore-event',
    accentColor: 'tomato red',
  },
  {
    id: 'cafe-seasonal',
    category: '餐饮空间',
    audience: '咖啡馆店主',
    product: '季节菜单 / 窗贴',
    brief: '海风、贝壳和一杯还没喝完的冷萃',
    visualGoal: '用一个贝壳或杯沿做主体，以单一亮色建立季节记忆。',
    whyItFits: '纸张纹理和克制色彩适合独立咖啡馆，而不是标准化连锁菜单。',
    deliverables: ['窗贴', '菜单封面', '外带杯插卡'],
    assetId: 'cafe-seasonal',
    accentColor: 'lemon yellow',
  },
  {
    id: 'art-exhibition',
    category: '艺术展览',
    audience: '策展人、画廊',
    product: '展览主视觉',
    brief: '台风经过之后，城市留下的两块天气碎片',
    visualGoal: '以双面板或局部切片表达观念，让观看距离成为展览的一部分。',
    whyItFits: 'Recipe 可以快速比较构图和色彩锚点，适合前期艺术指导。',
    deliverables: ['主海报', '展签', '邀请函'],
    assetId: 'art-exhibition',
    accentColor: 'ultramarine',
  },
  {
    id: 'poetry-book',
    category: '文学出版',
    audience: '作者、文学编辑',
    product: '诗歌 / 短篇小说封面',
    brief: '夜里没有人打开的门',
    visualGoal: '让少量物件和大面积留白先传达情绪，再留下文字层级。',
    whyItFits: '它把“情绪”转成可见的纸张、物件、位置和色彩规则。',
    deliverables: ['书封', '章节扉页', '电子书封面'],
    assetId: 'poetry-book',
    accentColor: 'magenta pink',
  },
  {
    id: 'music-ep-cover',
    category: '音乐发行',
    audience: '音乐人、唱片厂牌',
    product: '单曲 / EP 封面',
    brief: '凌晨两点，海边收音机里的低频回声',
    visualGoal: '用一个小型声音符号和饱和色块建立可识别的听觉封面。',
    whyItFits: '克制构图能让封面保留独立音乐的气质，不被复杂画面抢走。',
    deliverables: ['数字专辑封面', '歌词卡', '宣传图'],
    assetId: 'music-ep-cover',
    accentColor: 'cobalt blue',
  },
  {
    id: 'museum-culture',
    category: '文化机构',
    audience: '博物馆、文化机构',
    product: '藏品研究主题海报',
    brief: '一枚被海风磨旧的地方性物件',
    visualGoal: '把物件从说明文字中抽离，用一张有距离感的编辑海报引发观看。',
    whyItFits: '纸张、档案感和单一色彩可以把文化信息转成不喧闹的视觉入口。',
    deliverables: ['展览导视', '公众号头图', '教育活动卡'],
    assetId: 'museum-culture',
    accentColor: 'tomato red',
  },
  {
    id: 'film-title-card',
    category: '影视创作',
    audience: '导演、制片人',
    product: '片名视觉 / 片头卡',
    brief: '夜门后面没有发生的故事',
    visualGoal: '让一个门或入口成为片名情绪的停顿，不堆叠电影海报元素。',
    whyItFits: '它能把一句故事构想压缩成主体、留白、色彩和印刷节奏。',
    deliverables: ['片头卡', '海报草案', '社交预告'],
    assetId: 'film-title-card',
    accentColor: 'lemon yellow',
  },
  {
    id: 'art-direction',
    category: '创意研究',
    audience: '设计师、创意总监',
    product: '情绪板 / 艺术指导页',
    brief: '一块钴蓝色、旧纸张、安静的窗',
    visualGoal: '快速比较构图、色彩、材质和情绪的组合，而不是直接交付终稿。',
    whyItFits: 'Recipe 和九字段可以把“感觉”拆成可讨论的设计决策。',
    deliverables: ['Moodboard', '提案页', '风格基准'],
    assetId: 'art-direction',
    accentColor: 'cobalt blue',
  },
  {
    id: 'postcard-insert',
    category: '品牌实体物料',
    audience: '小型品牌、独立商店',
    product: '随货明信片 / 包装插页',
    brief: '一件被妥善保存的小物和一句短祝福',
    visualGoal: '让包装内页有触感和克制的感谢感，而不是标准促销卡。',
    whyItFits: '留白和纸张感能把一次购买变成更有记忆的实体接触。',
    deliverables: ['明信片', '包装插页', '会员感谢卡'],
    assetId: 'postcard-insert',
    accentColor: 'ultramarine',
  },
];

export const FULL_COPY_SAMPLE = {
  scenarioId: 'bookstore-event',
  assetPath: 'assets/generated/scenarios/bookstore-event.jpeg',
  eyebrow: 'WEEKEND READING SESSION',
  title: '闭店之后，读一会儿',
  date: '9月14日 周六 · 19:30',
  location: 'OLD BOOKSTORE / ROOM 02',
  description: '带一本正在读的书来，交换一个不急着结束的晚上。',
  footer: 'BOOKSTORE 02 · AFTER HOURS READING',
};
