import json

base = {"version": 1, "templates": []}

schemas = {
  "bar-chart-grow": [{"id":"title","type":"string","label":"图表标题","default":"2024 年度业绩"},{"id":"subtitle","type":"string","label":"副标题","default":"各部门季度销售额对比"},{"id":"labels","type":"string","label":"标签（逗号分隔）","default":"Q1,Q2,Q3,Q4,全年"},{"id":"values","type":"string","label":"数值（逗号分隔）","default":"45,72,58,91,85"},{"id":"colors","type":"string","label":"颜色（逗号分隔）","default":"#FF5A36,#FF5A36,#B8ADA2,#FF5A36,#D8CEC4"},{"id":"accent","type":"color","label":"强调色","default":"#FF5A36"},{"id":"background","type":"color","label":"背景色","default":"#12100E"},{"id":"foreground","type":"color","label":"文字色","default":"#F4EFE7"},{"id":"exportMode","type":"enum","label":"导出模式","default":"transparent","hidden":True,"options":[{"value":"transparent","label":"透明背景"},{"value":"mp4","label":"剪映 MP4 深色底"}]}],
  "number-counter": [{"id":"title","type":"string","label":"标题","default":"累计用户数"},{"id":"targetValue","type":"number","label":"目标数值","default":1285000},{"id":"prefix","type":"string","label":"前缀","default":""},{"id":"suffix","type":"string","label":"后缀","default":"+"},{"id":"note","type":"string","label":"补充说明","default":"突破百万里程碑，持续增长中"},{"id":"accent","type":"color","label":"强调色","default":"#FF5A36"},{"id":"background","type":"color","label":"背景色","default":"#12100E"},{"id":"foreground","type":"color","label":"文字色","default":"#F4EFE7"},{"id":"exportMode","type":"enum","label":"导出模式","default":"transparent","hidden":True,"options":[{"value":"transparent","label":"透明背景"},{"value":"mp4","label":"剪映 MP4 深色底"}]}],
  "line-chart-draw": [{"id":"title","type":"string","label":"图表标题","default":"月活跃用户增长趋势"},{"id":"subtitle","type":"string","label":"副标题","default":"2024.01 — 2024.12"},{"id":"labels","type":"string","label":"X轴标签（逗号分隔）","default":"1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月"},{"id":"values","type":"string","label":"Y轴数值（逗号分隔）","default":"120,145,180,210,260,340,420,480,510,580,640,720"},{"id":"accent","type":"color","label":"强调色","default":"#FF5A36"},{"id":"background","type":"color","label":"背景色","default":"#12100E"},{"id":"foreground","type":"color","label":"文字色","default":"#F4EFE7"},{"id":"exportMode","type":"enum","label":"导出模式","default":"transparent","hidden":True,"options":[{"value":"transparent","label":"透明背景"},{"value":"mp4","label":"剪映 MP4 深色底"}]}],
  "metric-pulse": [{"id":"headline","type":"string","label":"主标题","default":"本周内容增长"},{"id":"value","type":"number","label":"核心数字","default":286},{"id":"unit","type":"string","label":"数字单位","default":"%"},{"id":"note","type":"string","label":"补充说明","default":"连续四周保持上升，爆款内容贡献了主要增量。"},{"id":"accent","type":"color","label":"强调色","default":"#FF5A36"},{"id":"background","type":"color","label":"背景色","default":"#12100E"},{"id":"foreground","type":"color","label":"文字色","default":"#F4EFE7"},{"id":"exportMode","type":"enum","label":"导出模式","default":"transparent","hidden":True,"options":[{"value":"transparent","label":"透明背景"},{"value":"mp4","label":"剪映 MP4 深色底"}]}],
  "big-number-card": [{"id":"eyebrow","type":"string","label":"角标","default":"核心结论"},{"id":"prefix","type":"string","label":"前缀","default":"效率提升"},{"id":"value","type":"number","label":"数字","default":3.2},{"id":"unit","type":"string","label":"单位","default":"倍"},{"id":"caption","type":"string","label":"说明","default":"同样的选题流程，AI 参与后从整理资料到产出初稿明显提速。"},{"id":"accent","type":"color","label":"强调色","default":"#FF5A36"},{"id":"foreground","type":"color","label":"文字色","default":"#F4EFE7"},{"id":"exportMode","type":"enum","label":"导出模式","default":"transparent","hidden":True,"options":[{"value":"transparent","label":"透明背景"},{"value":"mp4","label":"剪映 MP4 深色底"}]}],
  "before-after-stat": [{"id":"label","type":"string","label":"主题","default":"做一条知识视频"},{"id":"beforeLabel","type":"string","label":"之前标签","default":"过去"},{"id":"beforeValue","type":"number","label":"之前数值","default":12},{"id":"afterLabel","type":"string","label":"之后标签","default":"现在"},{"id":"afterValue","type":"number","label":"之后数值","default":3},{"id":"unit","type":"string","label":"单位","default":"小时"},{"id":"conclusion","type":"string","label":"结论","default":"流程被压缩到原来的 1/4"},{"id":"accent","type":"color","label":"强调色","default":"#FF5A36"},{"id":"foreground","type":"color","label":"文字色","default":"#F4EFE7"},{"id":"exportMode","type":"enum","label":"导出模式","default":"transparent","hidden":True,"options":[{"value":"transparent","label":"透明背景"},{"value":"mp4","label":"剪映 MP4 深色底"}]}],
  "horizontal-bar-compare": [{"id":"title","type":"string","label":"标题","default":"两种方法的效率差距"},{"id":"itemA","type":"string","label":"项目 A","default":"传统整理"},{"id":"valueA","type":"number","label":"数值 A","default":42},{"id":"itemB","type":"string","label":"项目 B","default":"AI 辅助"},{"id":"valueB","type":"number","label":"数值 B","default":86},{"id":"unit","type":"string","label":"单位","default":"%"},{"id":"caption","type":"string","label":"结论","default":"AI 辅助在资料聚合和初稿生成阶段优势更明显。"},{"id":"accent","type":"color","label":"强调色","default":"#FF5A36"},{"id":"foreground","type":"color","label":"文字色","default":"#F4EFE7"},{"id":"exportMode","type":"enum","label":"导出模式","default":"transparent","hidden":True,"options":[{"value":"transparent","label":"透明背景"},{"value":"mp4","label":"剪映 MP4 深色底"}]}],
  "top-rank-list": [{"id":"title","type":"string","label":"标题","default":"影响效率的 Top 3 因素"},{"id":"rank1","type":"string","label":"第一名","default":"资料分散"},{"id":"value1","type":"number","label":"第一名数值","default":48},{"id":"rank2","type":"string","label":"第二名","default":"缺少模板"},{"id":"value2","type":"number","label":"第二名数值","default":31},{"id":"rank3","type":"string","label":"第三名","default":"反复改稿"},{"id":"value3","type":"number","label":"第三名数值","default":21},{"id":"unit","type":"string","label":"单位","default":"%"},{"id":"caption","type":"string","label":"说明","default":"真正拖慢生产的，往往不是创意，而是重复整理和重复决策。"},{"id":"accent","type":"color","label":"强调色","default":"#FF5A36"},{"id":"foreground","type":"color","label":"文字色","default":"#F4EFE7"},{"id":"exportMode","type":"enum","label":"导出模式","default":"transparent","hidden":True,"options":[{"value":"transparent","label":"透明背景"},{"value":"mp4","label":"剪映 MP4 深色底"}]}],
  "turning-point-line": [{"id":"title","type":"string","label":"标题","default":"增长真正的拐点"},{"id":"subtitle","type":"string","label":"副标题","default":"不是换工具，而是把流程模板化之后"},{"id":"pointLabel","type":"string","label":"拐点标签","default":"模板化开始"},{"id":"caption","type":"string","label":"结论","default":"拐点出现后，内容生产从单次项目变成可复用系统。"},{"id":"accent","type":"color","label":"强调色","default":"#FF5A36"},{"id":"foreground","type":"color","label":"文字色","default":"#F4EFE7"},{"id":"exportMode","type":"enum","label":"导出模式","default":"transparent","hidden":True,"options":[{"value":"transparent","label":"透明背景"},{"value":"mp4","label":"剪映 MP4 深色底"}]}],
  "source-citation-card": [{"id":"source","type":"string","label":"来源","default":"数据来源：项目复盘记录"},{"id":"date","type":"string","label":"日期","default":"2026.07"},{"id":"claim","type":"string","label":"结论","default":"模板化之后，重复动效制作时间明显下降"},{"id":"value","type":"number","label":"数字","default":68},{"id":"unit","type":"string","label":"单位","default":"%"},{"id":"note","type":"string","label":"补充说明","default":"统计口径：同类型知识视频中的数据展示片段。"},{"id":"accent","type":"color","label":"强调色","default":"#FF5A36"},{"id":"foreground","type":"color","label":"文字色","default":"#F4EFE7"},{"id":"exportMode","type":"enum","label":"导出模式","default":"transparent","hidden":True,"options":[{"value":"transparent","label":"透明背景"},{"value":"mp4","label":"剪映 MP4 深色底"}]}],
  "stat-duel": [{"id":"leftLabel","type":"string","label":"左侧标签","default":"上海 SHANGHAI"},{"id":"leftValue","type":"number","label":"左侧数值","default":92},{"id":"leftUnit","type":"string","label":"左侧单位","default":"%"},{"id":"rightLabel","type":"string","label":"右侧标签","default":"亚马逊 AMAZON"},{"id":"rightValue","type":"number","label":"右侧数值","default":90},{"id":"rightUnit","type":"string","label":"右侧单位","default":"%"},{"id":"operator","type":"enum","label":"比较符号","default":">","options":[{"value":">","label":"大于"},{"value":"=","label":"等于"},{"value":"<","label":"小于"}]},{"id":"verdict","type":"string","label":"结论","default":"上海湿度更高"},{"id":"accent","type":"color","label":"强调色","default":"#FF5A36"},{"id":"foreground","type":"color","label":"文字色","default":"#F4EFE7"},{"id":"exportMode","type":"enum","label":"导出模式","default":"transparent","hidden":True,"options":[{"value":"transparent","label":"透明背景"},{"value":"mp4","label":"剪映 MP4 深色底"}]}],
  "status-split": [{"id":"leftTitle","type":"string","label":"左侧状态","default":"往年常规"},{"id":"leftTag","type":"string","label":"左侧标签","default":"稳定期"},{"id":"rightTitle","type":"string","label":"右侧状态","default":"2026 异常"},{"id":"rightTag","type":"string","label":"右侧标签","default":"高温 · 潮湿"},{"id":"connector","type":"string","label":"转折词","default":"转向"},{"id":"accent","type":"color","label":"强调色","default":"#FF5A36"},{"id":"foreground","type":"color","label":"文字色","default":"#F4EFE7"},{"id":"exportMode","type":"enum","label":"导出模式","default":"transparent","hidden":True,"options":[{"value":"transparent","label":"透明背景"},{"value":"mp4","label":"剪映 MP4 深色底"}]}],
  "number-impact": [{"id":"hero","type":"string","label":"巨型关键词","default":"汉"},{"id":"label","type":"string","label":"指标名称","default":"体感湿度"},{"id":"value","type":"number","label":"百分比数值","default":100},{"id":"unit","type":"string","label":"单位","default":"%"},{"id":"caption","type":"string","label":"结论","default":"接近饱和"},{"id":"accent","type":"color","label":"强调色","default":"#FF5A36"},{"id":"foreground","type":"color","label":"文字色","default":"#F4EFE7"},{"id":"exportMode","type":"enum","label":"导出模式","default":"transparent","hidden":True,"options":[{"value":"transparent","label":"透明背景"},{"value":"mp4","label":"剪映 MP4 深色底"}]}],
  "concept-spotlight": [{"id":"label","type":"string","label":"标签","default":"核心概念"},{"id":"term","type":"string","label":"概念名","default":"提示词工程"},{"id":"definition","type":"string","label":"解释","default":"不是把问题说复杂，而是把目标、约束和判断标准说清楚。"},{"id":"note","type":"string","label":"补充说明","default":"适合解释术语 / 方法 / 心智模型"},{"id":"accent","type":"color","label":"强调色","default":"#FF5A36"},{"id":"foreground","type":"color","label":"文字色","default":"#F4EFE7"},{"id":"exportMode","type":"enum","label":"导出模式","default":"transparent","hidden":True,"options":[{"value":"transparent","label":"透明背景"},{"value":"mp4","label":"剪映 MP4 深色底"}]}],
  "three-step-flow": [{"id":"title","type":"string","label":"标题","default":"把知识讲清楚的三步"},{"id":"step1","type":"string","label":"步骤一","default":"定义问题"},{"id":"desc1","type":"string","label":"步骤一说明","default":"先说它解决什么"},{"id":"step2","type":"string","label":"步骤二","default":"拆开机制"},{"id":"desc2","type":"string","label":"步骤二说明","default":"再讲为什么成立"},{"id":"step3","type":"string","label":"步骤三","default":"给出动作"},{"id":"desc3","type":"string","label":"步骤三说明","default":"最后落到怎么做"},{"id":"accent","type":"color","label":"强调色","default":"#FF5A36"},{"id":"foreground","type":"color","label":"文字色","default":"#F4EFE7"},{"id":"exportMode","type":"enum","label":"导出模式","default":"transparent","hidden":True,"options":[{"value":"transparent","label":"透明背景"},{"value":"mp4","label":"剪映 MP4 深色底"}]}],
  "myth-fact-swap": [{"id":"mythLabel","type":"string","label":"误区标签","default":"常见误区"},{"id":"myth","type":"string","label":"误区","default":"AI 会直接替你思考"},{"id":"factLabel","type":"string","label":"事实标签","default":"更准确的说法"},{"id":"fact","type":"string","label":"事实","default":"AI 会放大你的问题定义能力"},{"id":"caption","type":"string","label":"总结","default":"重点不是替代，而是协作结构"},{"id":"accent","type":"color","label":"强调色","default":"#FF5A36"},{"id":"foreground","type":"color","label":"文字色","default":"#F4EFE7"},{"id":"exportMode","type":"enum","label":"导出模式","default":"transparent","hidden":True,"options":[{"value":"transparent","label":"透明背景"},{"value":"mp4","label":"剪映 MP4 深色底"}]}],
  "key-point-marker": [{"id":"kicker","type":"string","label":"提示词","default":"记住这一点"},{"id":"point","type":"string","label":"重点句","default":"真正拉开差距的不是工具，而是你拆问题的能力。"},{"id":"source","type":"string","label":"说明","default":"适合结论句 / 金句 / 操作提醒"},{"id":"accent","type":"color","label":"强调色","default":"#FF5A36"},{"id":"foreground","type":"color","label":"文字色","default":"#F4EFE7"},{"id":"exportMode","type":"enum","label":"导出模式","default":"transparent","hidden":True,"options":[{"value":"transparent","label":"透明背景"},{"value":"mp4","label":"剪映 MP4 深色底"}]}],
  "checklist-pop": [{"id":"title","type":"string","label":"标题","default":"上线前检查"},{"id":"item1","type":"string","label":"清单一","default":"默认文案能直接生成视频"},{"id":"item2","type":"string","label":"清单二","default":"透明 MOV 可以叠到剪辑里"},{"id":"item3","type":"string","label":"清单三","default":"模板能通过修改数据复用"},{"id":"accent","type":"color","label":"强调色","default":"#FF5A36"},{"id":"foreground","type":"color","label":"文字色","default":"#F4EFE7"},{"id":"exportMode","type":"enum","label":"导出模式","default":"transparent","hidden":True,"options":[{"value":"transparent","label":"透明背景"},{"value":"mp4","label":"剪映 MP4 深色底"}]}],
  "timeline-scan": [{"id":"title","type":"string","label":"标题","default":"从想法到系统"},{"id":"time1","type":"string","label":"节点一编号","default":"01"},{"id":"label1","type":"string","label":"节点一","default":"做一次"},{"id":"time2","type":"string","label":"节点二编号","default":"02"},{"id":"label2","type":"string","label":"节点二","default":"存模板"},{"id":"time3","type":"string","label":"节点三编号","default":"03"},{"id":"label3","type":"string","label":"节点三","default":"反复生成"},{"id":"accent","type":"color","label":"强调色","default":"#FF5A36"},{"id":"foreground","type":"color","label":"文字色","default":"#F4EFE7"},{"id":"exportMode","type":"enum","label":"导出模式","default":"transparent","hidden":True,"options":[{"value":"transparent","label":"透明背景"},{"value":"mp4","label":"剪映 MP4 深色底"}]}],
  "cause-chain": [{"id":"title","type":"string","label":"标题","default":"为什么效率会提升？"},{"id":"cause","type":"string","label":"原因","default":"重复动效被模板化"},{"id":"mechanism","type":"string","label":"机制","default":"只修改文案和数据"},{"id":"result","type":"string","label":"结果","default":"新视频能快速生成"},{"id":"accent","type":"color","label":"强调色","default":"#FF5A36"},{"id":"foreground","type":"color","label":"文字色","default":"#F4EFE7"},{"id":"exportMode","type":"enum","label":"导出模式","default":"transparent","hidden":True,"options":[{"value":"transparent","label":"透明背景"},{"value":"mp4","label":"剪映 MP4 深色底"}]}],
}

templates_meta = [
  ("bar-chart-grow","柱状图增长","3–7 根垂直柱形从底部弹性增长，带数值标签与网格线，适合业绩对比、多维度数据分布。","数据可视化",["柱状图","增长","对比","多系列"],6,"1920×1080",["mp4","mov","webm"],"mp4","https://yydshly.github.io/0730_practical-skill-study/hyperframes-motion-library/renders/bar-chart-grow/sample.mp4"),
  ("number-counter","数字计数器","巨型数字从 0 滚动到目标值，可选环形进度条，适合里程碑、KPI、累计数据展示。","数据可视化",["数字","计数器","滚动","KPI","里程碑"],5,"1920×1080",["mp4","mov","webm"],"mp4","https://yydshly.github.io/0730_practical-skill-study/hyperframes-motion-library/renders/number-counter/sample.mp4"),
  ("line-chart-draw","折线绘制","折线从左侧逐段绘制到右侧，数据点依次弹出，下方填充区域晕染展开，适合时间序列趋势。","数据可视化",["折线图","趋势","时间序列","绘制动画"],7,"1920×1080",["mp4","mov","webm"],"mp4","https://yydshly.github.io/0730_practical-skill-study/hyperframes-motion-library/renders/line-chart-draw/sample.mp4"),
  ("metric-pulse","数据脉冲","适合增长数据、里程碑、成绩与单项 KPI 的横屏数据动效。","数据可视化",["数据","增长","里程碑","横屏"],6,"1920×1080",["mp4","mov","webm"],"mp4","https://yydshly.github.io/0730_practical-skill-study/hyperframes-motion-library/renders/metric-pulse/sample.mp4"),
  ("big-number-card","大数字结论卡","用一个巨型数字和一句解释承接核心结论，适合知识视频里的效率、成本、提升幅度表达。","数据可视化",["数字","结论","效率","知识视频"],5,"1920×1080",["mp4","mov","webm"],"mp4","https://yydshly.github.io/0730_practical-skill-study/hyperframes-motion-library/renders/big-number-card/sample.webm"),
  ("before-after-stat","前后对比数字","把过去与现在、旧方法与新方法的关键数字做成强对比，适合讲工具提效和流程改造。","数据可视化",["前后对比","效率","数字","方法论"],5.5,"1920×1080",["mp4","mov","webm"],"mp4","https://yydshly.github.io/0730_practical-skill-study/hyperframes-motion-library/renders/before-after-stat/sample.webm"),
  ("horizontal-bar-compare","横向条形对比","两组指标横向条形展开，适合传统方法 vs 新方法、两个工具或两个对象的快速比较。","数据可视化",["条形图","对比","方法","百分比"],5.5,"1920×1080",["mp4","mov","webm"],"mp4","https://yydshly.github.io/0730_practical-skill-study/hyperframes-motion-library/renders/horizontal-bar-compare/sample.webm"),
  ("top-rank-list","Top 排名卡","三条排名逐条弹出，适合工具推荐、影响因素排序、原因权重和 Top 3/Top 5 类内容。","数据可视化",["排名","Top3","列表","权重"],5.5,"1920×1080",["mp4","mov","webm"],"mp4","https://yydshly.github.io/0730_practical-skill-study/hyperframes-motion-library/renders/top-rank-list/sample.webm"),
  ("turning-point-line","拐点趋势线","趋势线绘制后点亮关键拐点，适合讲增长变化、版本演进、方法生效的关键时刻。","数据可视化",["趋势","拐点","折线","增长"],6,"1920×1080",["mp4","mov","webm"],"mp4","https://yydshly.github.io/0730_practical-skill-study/hyperframes-motion-library/renders/turning-point-line/sample.webm"),
  ("source-citation-card","数据来源引用卡","下三分之一引用卡展示来源、日期、核心数字和统计口径，适合给知识视频增加可信度。","知识讲解",["引用","来源","证据","数据"],5,"1920×1080",["mp4","mov","webm"],"mp4","https://yydshly.github.io/0730_practical-skill-study/hyperframes-motion-library/renders/source-citation-card/sample.webm"),
  ("stat-duel","双数据对比","两组明确数据的横向对比，可透明叠加在实拍画面底部。","透明叠加",["对比","百分比","透明","纪录片"],5,"1920×1080",["mp4","mov","webm"],"mp4","https://yydshly.github.io/0730_practical-skill-study/hyperframes-motion-library/renders/stat-duel/sample.webm"),
  ("status-split","状态转折","把常规与异常、过去与现在等两种状态做成章节式对照。","透明叠加",["对照","章节","透明","转折"],5,"1920×1080",["mp4","mov","webm"],"mp4","https://yydshly.github.io/0730_practical-skill-study/hyperframes-motion-library/renders/status-split/sample.webm"),
  ("number-impact","极值刻度","巨型关键词、单项百分比与同值刻度组成的冲击型叠加动效。","透明叠加",["数字","刻度","百分比","透明"],5,"1920×1080",["mp4","mov","webm"],"mp4","https://yydshly.github.io/0730_practical-skill-study/hyperframes-motion-library/renders/number-impact/sample.webm"),
  ("concept-spotlight","概念解释卡","透明玻璃卡片聚焦一个概念名、解释句和补充提示，适合知识视频里的术语解释、方法论定义。","知识讲解",["概念","解释","术语","透明"],5,"1920×1080",["mp4","mov","webm"],"mp4","https://yydshly.github.io/0730_practical-skill-study/hyperframes-motion-library/renders/concept-spotlight/sample.webm"),
  ("three-step-flow","三步流程","三个步骤卡片与连接线依次生长，适合 SOP、教程步骤、知识框架的口播叠加。","知识讲解",["步骤","流程","教程","透明"],6,"1920×1080",["mp4","mov","webm"],"mp4","https://yydshly.github.io/0730_practical-skill-study/hyperframes-motion-library/renders/three-step-flow/sample.webm"),
  ("myth-fact-swap","误区纠正",'把"常见误区"划掉并切换到"真实情况"，适合观点纠偏、认知反转、知识澄清。',"知识讲解",["误区","纠正","反转","透明"],5.5,"1920×1080",["mp4","mov","webm"],"mp4","https://yydshly.github.io/0730_practical-skill-study/hyperframes-motion-library/renders/myth-fact-swap/sample.webm"),
  ("key-point-marker","重点标注","下三分之一的重点句标注动效，带角标和扫描下划线，适合金句、结论和操作提醒。","知识讲解",["重点","标注","金句","透明"],4.5,"1920×1080",["mp4","mov","webm"],"mp4","https://yydshly.github.io/0730_practical-skill-study/hyperframes-motion-library/renders/key-point-marker/sample.webm"),
  ("checklist-pop","清单核对","三条检查项逐条弹出并完成勾选，适合总结步骤、注意事项、行动清单。","知识讲解",["清单","勾选","总结","透明"],5,"1920×1080",["mp4","mov","webm"],"mp4","https://yydshly.github.io/0730_practical-skill-study/hyperframes-motion-library/renders/checklist-pop/sample.webm"),
  ("timeline-scan","时间线推进","三个时间节点沿路径依次点亮，适合讲版本变化、阶段推进、历史演变。","知识讲解",["时间线","阶段","演变","透明"],5.5,"1920×1080",["mp4","mov","webm"],"mp4","https://yydshly.github.io/0730_practical-skill-study/hyperframes-motion-library/renders/timeline-scan/sample.webm"),
  ("cause-chain","因果链路","原因、机制、结果三段式链路，适合解释为什么、怎么发生、带来什么结果。","知识讲解",["因果","机制","解释","透明"],5.5,"1920×1080",["mp4","mov","webm"],"mp4","https://yydshly.github.io/0730_practical-skill-study/hyperframes-motion-library/renders/cause-chain/sample.webm"),
]

for (tid,name,desc,cat,tags,dur,size,fmts,def_fmt,preview) in templates_meta:
    schema = schemas[tid]
    defaults = {f["id"]: f["default"] for f in schema}
    base["templates"].append({
        "id": tid,
        "name": name,
        "description": desc,
        "path": f"templates/{tid}",
        "category": cat,
        "tags": tags,
        "duration": dur,
        "size": size,
        "formats": fmts,
        "defaultFormat": def_fmt,
        "preview": preview,
        "status": "ready",
        "schema": schema,
        "presets": [{"id": "default", "values": defaults}]
    })

with open("catalog.static.json", "w", encoding="utf-8") as f:
    json.dump(base, f, ensure_ascii=False, indent=2)

print(f"Done, wrote {len(base['templates'])} templates")
